"use client";

import { CodeDisclosure } from "@/components/code-disclosure";

const code = "// Modified for Supervisor previews. License: Apache 2.0.\n\"use client\";\n\nimport {\n  Agent,\n  AgentContent,\n  AgentHeader,\n  AgentInstructions,\n  AgentOutput,\n  AgentTool,\n  AgentTools,\n} from \"@/components/ai-elements/agent\";\nimport { z } from \"zod\";\n\nconst webSearchTool = {\n  description: \"Search the web for information\",\n  inputSchema: z.object({\n    query: z.string().describe(\"The search query\"),\n  }),\n};\n\nconst readUrlTool = {\n  description: \"Read and parse a URL\",\n  inputSchema: z.object({\n    url: z.string().url().describe(\"The URL to read\"),\n  }),\n};\n\nconst summarizeTool = {\n  description: \"Summarize text into key points\",\n  inputSchema: z.object({\n    maxPoints: z.number().optional().describe(\"Maximum number of key points\"),\n    text: z.string().describe(\"The text to summarize\"),\n  }),\n};\n\nconst outputSchema = `z.object({\n  sentiment: z.enum(['positive', 'negative', 'neutral']),\n  score: z.number(),\n  summary: z.string(),\n})`;\n\nconst Example = () => (\n  <Agent>\n    <AgentHeader model=\"openai/gpt-5.2-pro\" name=\"Research Assistant\" />\n    <AgentContent>\n      <AgentInstructions>\n        You are a helpful research assistant. Your job is to search the web for\n        information and summarize findings for the user. Always cite your\n        sources and provide accurate, up-to-date information.\n      </AgentInstructions>\n      <AgentTools type=\"multiple\">\n        <AgentTool tool={webSearchTool} value=\"web_search\" />\n        <AgentTool tool={readUrlTool} value=\"read_url\" />\n        <AgentTool tool={summarizeTool} value=\"summarize\" />\n      </AgentTools>\n      <AgentOutput schema={outputSchema} />\n    </AgentContent>\n  </Agent>\n);\n\nexport default Example;";

export default function AIElementSnippet({ title }: { title: string }) {
  return <CodeDisclosure title={title} code={code} />;
}
