"use client";

import { CodeDisclosure } from "@/components/code-disclosure";

const code = "// Modified for Supervisor previews. License: Apache 2.0.\n\"use client\";\n\nimport {\n  Attachment,\n  AttachmentPreview,\n  AttachmentRemove,\n  Attachments,\n} from \"@/components/ai-elements/attachments\";\nimport { nanoid } from \"nanoid\";\nimport { memo, useCallback, useState } from \"react\";\n\nconst initialAttachments = [\n  {\n    filename: \"mountain-landscape.jpg\",\n    id: nanoid(),\n    mediaType: \"image/jpeg\",\n    type: \"file\" as const,\n    url: \"https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=400&fit=crop\",\n  },\n  {\n    filename: \"ocean-sunset.jpg\",\n    id: nanoid(),\n    mediaType: \"image/jpeg\",\n    type: \"file\" as const,\n    url: \"https://images.unsplash.com/photo-1682687220742-aba13b6e50ba?w=400&h=400&fit=crop\",\n  },\n  {\n    filename: \"document.pdf\",\n    id: nanoid(),\n    mediaType: \"application/pdf\",\n    type: \"file\" as const,\n    url: \"\",\n  },\n  {\n    filename: \"video.mp4\",\n    id: nanoid(),\n    mediaType: \"video/mp4\",\n    type: \"file\" as const,\n    url: \"\",\n  },\n];\n\ninterface AttachmentItemProps {\n  attachment: (typeof initialAttachments)[0];\n  onRemove: (id: string) => void;\n}\n\nconst AttachmentItem = memo(({ attachment, onRemove }: AttachmentItemProps) => {\n  const handleRemove = useCallback(\n    () => onRemove(attachment.id),\n    [onRemove, attachment.id]\n  );\n  return (\n    <Attachment data={attachment} onRemove={handleRemove}>\n      <AttachmentPreview />\n      <AttachmentRemove />\n    </Attachment>\n  );\n});\n\nAttachmentItem.displayName = \"AttachmentItem\";\n\nconst Example = () => {\n  const [attachments, setAttachments] = useState(initialAttachments);\n\n  const handleRemove = useCallback((id: string) => {\n    setAttachments((prev) => prev.filter((a) => a.id !== id));\n  }, []);\n\n  return (\n    <div className=\"flex items-center justify-center p-8\">\n      <Attachments variant=\"grid\">\n        {attachments.map((attachment) => (\n          <AttachmentItem\n            attachment={attachment}\n            key={attachment.id}\n            onRemove={handleRemove}\n          />\n        ))}\n      </Attachments>\n    </div>\n  );\n};\n\nexport default Example;";

export default function AIElementSnippet({ title }: { title: string }) {
  return <CodeDisclosure title={title} code={code} />;
}
