"use client";

import { CodeDisclosure } from "@/components/code-disclosure";

const code = "// Modified for Supervisor previews. License: Apache 2.0.\n\"use client\";\n\nimport { toast } from \"sonner\";\nimport {\n  Commit,\n  CommitActions,\n  CommitAuthor,\n  CommitAuthorAvatar,\n  CommitContent,\n  CommitCopyButton,\n  CommitFile,\n  CommitFileAdditions,\n  CommitFileChanges,\n  CommitFileDeletions,\n  CommitFileIcon,\n  CommitFileInfo,\n  CommitFilePath,\n  CommitFileStatus,\n  CommitFiles,\n  CommitHash,\n  CommitHeader,\n  CommitInfo,\n  CommitMessage,\n  CommitMetadata,\n  CommitSeparator,\n  CommitTimestamp,\n} from \"@/components/ai-elements/commit\";\n\nconst handleCopy = () => {\n  toast.success(\"Commit hash copied\");\n};\n\nconst hash = \"a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0\";\nconst timestamp = new Date(Date.now() - 1000 * 60 * 60 * 2);\n\nconst files = [\n  {\n    additions: 150,\n    deletions: 0,\n    path: \"src/auth/login.tsx\",\n    status: \"added\" as const,\n  },\n  {\n    additions: 45,\n    deletions: 0,\n    path: \"src/auth/logout.tsx\",\n    status: \"added\" as const,\n  },\n  {\n    additions: 23,\n    deletions: 8,\n    path: \"src/lib/session.ts\",\n    status: \"modified\" as const,\n  },\n];\n\nconst Example = () => (\n  <Commit>\n    <CommitHeader>\n      <CommitAuthor>\n        <CommitAuthorAvatar initials=\"HB\" />\n      </CommitAuthor>\n      <CommitInfo>\n        <CommitMessage>feat: Add user authentication flow</CommitMessage>\n        <CommitMetadata>\n          <CommitHash>{hash.slice(0, 7)}</CommitHash>\n          <CommitSeparator />\n          <CommitTimestamp date={timestamp} />\n        </CommitMetadata>\n      </CommitInfo>\n      <CommitActions>\n        <CommitCopyButton hash={hash} onCopy={handleCopy} />\n      </CommitActions>\n    </CommitHeader>\n    <CommitContent>\n      <CommitFiles>\n        {files.map((file) => (\n          <CommitFile key={file.path}>\n            <CommitFileInfo>\n              <CommitFileStatus status={file.status} />\n              <CommitFileIcon />\n              <CommitFilePath>{file.path}</CommitFilePath>\n            </CommitFileInfo>\n            <CommitFileChanges>\n              <CommitFileAdditions count={file.additions} />\n              <CommitFileDeletions count={file.deletions} />\n            </CommitFileChanges>\n          </CommitFile>\n        ))}\n      </CommitFiles>\n    </CommitContent>\n  </Commit>\n);\n\nexport default Example;";

export default function AIElementSnippet({ title }: { title: string }) {
  return <CodeDisclosure title={title} code={code} />;
}
