"use client";

import { CodeDisclosure } from "@/components/code-disclosure";

const code = "// Modified for Supervisor previews. License: Apache 2.0.\n\"use client\";\n\nimport {\n  Confirmation,\n  ConfirmationAccepted,\n  ConfirmationAction,\n  ConfirmationActions,\n  ConfirmationRejected,\n  ConfirmationRequest,\n  ConfirmationTitle,\n} from \"@/components/ai-elements/confirmation\";\nimport { CheckIcon, XIcon } from \"lucide-react\";\nimport { useState } from \"react\";\n\ntype Decision = \"pending\" | \"approved\" | \"rejected\";\n\nconst Example = () => {\n  const [decision, setDecision] = useState<Decision>(\"pending\");\n  const approval = decision === \"pending\"\n    ? { id: \"delete-example\" }\n    : { id: \"delete-example\", approved: decision === \"approved\" };\n  const state = decision === \"pending\" ? \"approval-requested\" : \"approval-responded\";\n\n  return (\n    <div className=\"w-full max-w-2xl\">\n      <Confirmation approval={approval} state={state}>\n      <ConfirmationTitle>\n        <ConfirmationRequest>\n          This tool wants to delete the file{\" \"}\n          <code className=\"inline rounded bg-muted px-1.5 py-0.5 text-sm\">\n            /tmp/example.txt\n          </code>\n          . Do you approve this action?\n        </ConfirmationRequest>\n        <ConfirmationAccepted>\n          <CheckIcon className=\"size-4 text-green-600 dark:text-green-400\" />\n          <span>You approved this tool execution</span>\n        </ConfirmationAccepted>\n        <ConfirmationRejected>\n          <XIcon className=\"size-4 text-destructive\" />\n          <span>You rejected this tool execution</span>\n        </ConfirmationRejected>\n      </ConfirmationTitle>\n      <ConfirmationActions>\n        <ConfirmationAction onClick={() => setDecision(\"rejected\")} variant=\"outline\">\n          Reject\n        </ConfirmationAction>\n        <ConfirmationAction onClick={() => setDecision(\"approved\")} variant=\"default\">\n          Approve\n        </ConfirmationAction>\n      </ConfirmationActions>\n      </Confirmation>\n    </div>\n  );\n};\n\nexport default Example;";

export default function AIElementSnippet({ title }: { title: string }) {
  return <CodeDisclosure title={title} code={code} />;
}
