"use client";

import { CodeDisclosure } from "@/components/code-disclosure";

const code = "// Modified for Supervisor previews. License: Apache 2.0.\n\"use client\";\n\nimport { toast } from \"sonner\";\nimport {\n  EnvironmentVariable,\n  EnvironmentVariableCopyButton,\n  EnvironmentVariableGroup,\n  EnvironmentVariableName,\n  EnvironmentVariableRequired,\n  EnvironmentVariables,\n  EnvironmentVariablesContent,\n  EnvironmentVariablesHeader,\n  EnvironmentVariablesTitle,\n  EnvironmentVariablesToggle,\n  EnvironmentVariableValue,\n} from \"@/components/ai-elements/environment-variables\";\n\nconst variables = [\n  {\n    name: \"DATABASE_URL\",\n    required: true,\n    value: \"postgresql://localhost:5432/mydb\",\n  },\n  { name: \"API_KEY\", required: true, value: \"sk-1234567890abcdef\" },\n  { name: \"NODE_ENV\", required: false, value: \"production\" },\n  { name: \"PORT\", required: false, value: \"3000\" },\n];\n\nconst handleCopy = () => {\n  toast.success(\"Copied\");\n};\n\nconst Example = () => (\n  <EnvironmentVariables defaultShowValues={false}>\n    <EnvironmentVariablesHeader>\n      <EnvironmentVariablesTitle />\n      <EnvironmentVariablesToggle />\n    </EnvironmentVariablesHeader>\n    <EnvironmentVariablesContent>\n      {variables.map((variable) => (\n        <EnvironmentVariable\n          key={variable.name}\n          name={variable.name}\n          value={variable.value}\n        >\n          <EnvironmentVariableGroup>\n            <EnvironmentVariableName />\n            {variable.required && <EnvironmentVariableRequired />}\n          </EnvironmentVariableGroup>\n          <EnvironmentVariableGroup>\n            <EnvironmentVariableValue />\n            <EnvironmentVariableCopyButton\n              copyFormat=\"export\"\n              onCopy={handleCopy}\n            />\n          </EnvironmentVariableGroup>\n        </EnvironmentVariable>\n      ))}\n    </EnvironmentVariablesContent>\n  </EnvironmentVariables>\n);\n\nexport default Example;";

export default function AIElementSnippet({ title }: { title: string }) {
  return <CodeDisclosure title={title} code={code} />;
}
