"use client";

import { CodeDisclosure } from "@/components/code-disclosure";

const code = "// Modified for Supervisor previews. License: Apache 2.0.\n\"use client\";\n\nimport type { PersonaState } from \"@/components/ai-elements/persona\";\nimport { Persona } from \"@/components/ai-elements/persona\";\nimport { Button } from \"@/components/ui/button\";\nimport { ButtonGroup } from \"@/components/ui/button-group\";\nimport {\n  Tooltip,\n  TooltipContent,\n  TooltipTrigger,\n} from \"@/components/ui/tooltip\";\nimport type { LucideIcon } from \"lucide-react\";\nimport {\n  BrainIcon,\n  CircleIcon,\n  EyeClosedIcon,\n  MegaphoneIcon,\n  MicIcon,\n} from \"lucide-react\";\nimport { memo, useCallback, useState } from \"react\";\n\nconst states: {\n  state: PersonaState;\n  icon: LucideIcon;\n  label: string;\n}[] = [\n  {\n    icon: CircleIcon,\n    label: \"Idle\",\n    state: \"idle\",\n  },\n  {\n    icon: MicIcon,\n    label: \"Listening\",\n    state: \"listening\",\n  },\n  {\n    icon: BrainIcon,\n    label: \"Thinking\",\n    state: \"thinking\",\n  },\n  {\n    icon: MegaphoneIcon,\n    label: \"Speaking\",\n    state: \"speaking\",\n  },\n  {\n    icon: EyeClosedIcon,\n    label: \"Asleep\",\n    state: \"asleep\",\n  },\n];\n\ninterface StateButtonProps {\n  state: (typeof states)[0];\n  currentState: PersonaState;\n  onStateChange: (state: PersonaState) => void;\n}\n\nconst StateButton = memo(\n  ({ state, currentState, onStateChange }: StateButtonProps) => {\n    const handleClick = useCallback(\n      () => onStateChange(state.state),\n      [onStateChange, state.state]\n    );\n    return (\n      <Tooltip key={state.state}>\n        <TooltipTrigger asChild>\n          <Button\n            aria-label={state.label}\n            onClick={handleClick}\n            size=\"icon-sm\"\n            variant={currentState === state.state ? \"default\" : \"outline\"}\n          >\n            <state.icon className=\"size-4\" />\n          </Button>\n        </TooltipTrigger>\n        <TooltipContent>{state.label}</TooltipContent>\n      </Tooltip>\n    );\n  }\n);\n\nStateButton.displayName = \"StateButton\";\n\nconst Example = () => {\n  const [currentState, setCurrentState] = useState<PersonaState>(\"idle\");\n\n  const handleStateChange = useCallback((state: PersonaState) => {\n    setCurrentState(state);\n  }, []);\n\n  return (\n    <div className=\"flex size-full flex-col items-center justify-center gap-4\">\n      <Persona className=\"size-32\" state={currentState} variant=\"halo\" />\n\n      <ButtonGroup orientation=\"horizontal\">\n        {states.map((state) => (\n          <StateButton\n            currentState={currentState}\n            key={state.state}\n            onStateChange={handleStateChange}\n            state={state}\n          />\n        ))}\n      </ButtonGroup>\n    </div>\n  );\n};\n\nexport default Example;";

export default function AIElementSnippet({ title }: { title: string }) {
  return <CodeDisclosure title={title} code={code} />;
}
