"use client";

import { CodeDisclosure } from "@/components/code-disclosure";

const code = "// Modified for Supervisor previews. License: Apache 2.0.\n\"use client\";\n\nimport { toast } from \"sonner\";\nimport {\n  StackTrace,\n  StackTraceActions,\n  StackTraceContent,\n  StackTraceCopyButton,\n  StackTraceError,\n  StackTraceErrorMessage,\n  StackTraceErrorType,\n  StackTraceExpandButton,\n  StackTraceFrames,\n  StackTraceHeader,\n} from \"@/components/ai-elements/stack-trace\";\n\nconst handleFilePathClick = (path: string, line?: number, col?: number) => {\n  toast(\"File selected\", { description: `${path}:${line ?? 1}:${col ?? 1}` });\n};\n\nconst handleCopy = () => {\n  toast.success(\"Stack trace copied\");\n};\n\nconst sampleStackTrace = `TypeError: Cannot read properties of undefined (reading 'map')\n    at UserList (/app/components/UserList.tsx:15:23)\n    at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:14985:18)\n    at mountIndeterminateComponent (node_modules/react-dom/cjs/react-dom.development.js:17811:13)\n    at beginWork (node_modules/react-dom/cjs/react-dom.development.js:19049:16)\n    at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:3945:14)\n    at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:3994:16)\n    at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:4056:31)\n    at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:23964:7)\n    at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:22776:12)\n    at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:22707:5)`;\n\nconst Example = () => (\n  <StackTrace\n    defaultOpen\n    onFilePathClick={handleFilePathClick}\n    trace={sampleStackTrace}\n  >\n    <StackTraceHeader>\n      <StackTraceError>\n        <StackTraceErrorType />\n        <StackTraceErrorMessage />\n      </StackTraceError>\n      <StackTraceActions>\n        <StackTraceCopyButton onCopy={handleCopy} />\n        <StackTraceExpandButton />\n      </StackTraceActions>\n    </StackTraceHeader>\n    <StackTraceContent>\n      <StackTraceFrames />\n    </StackTraceContent>\n  </StackTrace>\n);\n\nexport default Example;";

export default function AIElementSnippet({ title }: { title: string }) {
  return <CodeDisclosure title={title} code={code} />;
}
