"use client";

import { CodeDisclosure } from "@/components/code-disclosure";

const code = "// Modified for Supervisor previews. License: Apache 2.0.\n\"use client\";\n\nimport { toast } from \"sonner\";\nimport {\n  Terminal,\n  TerminalActions,\n  TerminalClearButton,\n  TerminalContent,\n  TerminalCopyButton,\n  TerminalHeader,\n  TerminalStatus,\n  TerminalTitle,\n} from \"@/components/ai-elements/terminal\";\nimport { useCallback, useEffect, useState } from \"react\";\n\nconst handleTerminalCopy = () => {\n  toast.success(\"Copied\");\n};\n\nconst ansiOutput = `\\u001B[32m✓\\u001B[0m Compiled successfully in 1.2s\n\n\\u001B[1m\\u001B[34minfo\\u001B[0m  - Collecting page data...\n\\u001B[1m\\u001B[34minfo\\u001B[0m  - Generating static pages (0/3)\n\\u001B[32m✓\\u001B[0m Generated static pages (3/3)\n\n\\u001B[1m\\u001B[33mwarn\\u001B[0m  - Using \\u001B[1mexperimental\\u001B[0m server actions\n\n\\u001B[36mRoute (app)\\u001B[0m                              \\u001B[36mSize\\u001B[0m     \\u001B[36mFirst Load JS\\u001B[0m\n\\u001B[37m┌ ○ /\\u001B[0m                                    \\u001B[32m5.2 kB\\u001B[0m   \\u001B[32m87.3 kB\\u001B[0m\n\\u001B[37m├ ○ /about\\u001B[0m                               \\u001B[32m2.1 kB\\u001B[0m   \\u001B[32m84.2 kB\\u001B[0m\n\\u001B[37m└ ○ /contact\\u001B[0m                             \\u001B[32m3.8 kB\\u001B[0m   \\u001B[32m85.9 kB\\u001B[0m\n\n\\u001B[32m✓\\u001B[0m Build completed successfully!\n\\u001B[90mTotal time: 3.45s\\u001B[0m\n`;\n\nconst Example = () => {\n  const [output, setOutput] = useState(\"\");\n  const [isStreaming, setIsStreaming] = useState(true);\n\n  useEffect(() => {\n    let index = 0;\n    const interval = setInterval(() => {\n      if (index < ansiOutput.length) {\n        setOutput(ansiOutput.slice(0, index + 10));\n        index += 10;\n      } else {\n        setIsStreaming(false);\n        clearInterval(interval);\n      }\n    }, 20);\n\n    return () => clearInterval(interval);\n  }, []);\n\n  const handleClear = useCallback(() => {\n    setOutput(\"\");\n    setIsStreaming(false);\n  }, []);\n\n  return (\n    <Terminal\n      autoScroll={true}\n      isStreaming={isStreaming}\n      onClear={handleClear}\n      output={output}\n    >\n      <TerminalHeader>\n        <TerminalTitle>Build Output</TerminalTitle>\n        <div className=\"flex items-center gap-1\">\n          <TerminalStatus />\n          <TerminalActions>\n            <TerminalCopyButton onCopy={handleTerminalCopy} />\n            <TerminalClearButton />\n          </TerminalActions>\n        </div>\n      </TerminalHeader>\n      <TerminalContent />\n    </Terminal>\n  );\n};\n\nexport default Example;";

export default function AIElementSnippet({ title }: { title: string }) {
  return <CodeDisclosure title={title} code={code} />;
}
