"use client";

import { CodeDisclosure } from "@/components/code-disclosure";

const code = "// Modified for Supervisor previews. License: Apache 2.0.\n\"use client\";\n\nimport { useState } from \"react\";\nimport { ArrowLeftIcon, ArrowRightIcon, Maximize2Icon, Minimize2Icon, RefreshCcwIcon } from \"lucide-react\";\nimport {\n  WebPreview,\n  WebPreviewBody,\n  WebPreviewConsole,\n  WebPreviewNavigation,\n  WebPreviewNavigationButton,\n  WebPreviewUrl,\n} from \"@/components/ai-elements/web-preview\";\n\nconst localDocument = `<!doctype html><html><body style=\"margin:0;background:#fafafa;color:#171717;font-family:system-ui\"><main style=\"padding:40px\"><p style=\"font:12px ui-monospace;color:#666\">LOCAL PREVIEW</p><h1 style=\"font-size:28px;letter-spacing:-.04em\">Quarterly research notes</h1><p style=\"max-width:42ch;line-height:1.6;color:#525252\">This iframe renders a fixed srcDoc string. It makes no network request.</p></main></body></html>`;\n\nexport default function WebPreviewExample() {\n  const [revision, setRevision] = useState(1);\n  const [expanded, setExpanded] = useState(false);\n  const logs = [{ level: \"log\" as const, message: `Local document loaded, revision ${revision}`, timestamp: new Date(\"2026-09-10T09:30:00Z\") }];\n  return (\n    <WebPreview defaultUrl=\"about:srcdoc\" className={expanded ? \"h-[520px]\" : \"h-[400px]\"}>\n      <WebPreviewNavigation>\n        <WebPreviewNavigationButton disabled tooltip=\"No earlier local page\" aria-label=\"Go back\"><ArrowLeftIcon className=\"size-4\" /></WebPreviewNavigationButton>\n        <WebPreviewNavigationButton disabled tooltip=\"No later local page\" aria-label=\"Go forward\"><ArrowRightIcon className=\"size-4\" /></WebPreviewNavigationButton>\n        <WebPreviewNavigationButton onClick={() => setRevision((value) => value + 1)} tooltip=\"Reload local document\" aria-label=\"Reload local document\"><RefreshCcwIcon className=\"size-4\" /></WebPreviewNavigationButton>\n        <WebPreviewUrl aria-label=\"Preview address\" readOnly value=\"about:srcdoc\" />\n        <WebPreviewNavigationButton aria-pressed={expanded} onClick={() => setExpanded((value) => !value)} tooltip={expanded ? \"Reduce preview\" : \"Expand preview\"} aria-label={expanded ? \"Reduce preview\" : \"Expand preview\"}>{expanded ? <Minimize2Icon className=\"size-4\" /> : <Maximize2Icon className=\"size-4\" />}</WebPreviewNavigationButton>\n      </WebPreviewNavigation>\n      <WebPreviewBody key={revision} srcDoc={localDocument} />\n      <WebPreviewConsole logs={logs} />\n    </WebPreview>\n  );\n}";

export default function AIElementSnippet({ title }: { title: string }) {
  return <CodeDisclosure title={title} code={code} />;
}
