export const ledgerMotion = {
  layout: { type: "spring", stiffness: 310, damping: 34, mass: 1 },
  enter: { type: "tween", duration: 0.22, ease: [0.22, 1, 0.36, 1] },
  exit: { type: "tween", duration: 0.26, ease: [0.4, 0, 0.6, 1] },
  summary: { type: "tween", duration: 0.12, ease: "easeInOut" },
  chart: { type: "tween", duration: 0.48, ease: [0.22, 1, 0.36, 1] },
  tooltip: { type: "tween", duration: 0.16, ease: [0.22, 1, 0.36, 1] },
} as const;

const ledgerNativeSans = '-apple-system, BlinkMacSystemFont, "SF Pro Text", "SF Pro Display", system-ui, sans-serif';

export const ledgerVariables: Record<string, string> = {
  "--ledger-font-body": ledgerNativeSans,
  "--ledger-font-heading": ledgerNativeSans,
  "--ledger-font-button": ledgerNativeSans,
  "--ledger-font-data": '"SFMono-Regular", Menlo, Consolas, "Liberation Mono", monospace',
  "--ledger-canvas": "#f3f3f3",
  "--ledger-paper": "#ffffff",
  "--ledger-ink": "#181818",
  "--ledger-muted": "#272727",
  "--ledger-foreground": "#232323",
  "--ledger-inverse": "#eeeeee",
  "--ledger-label": "#969696",
  "--ledger-label-contrast": "#595959",
  "--ledger-destructive": "#b42318",
  "--ledger-series-1": "#232323",
  "--ledger-series-2": "#707070",
  "--ledger-series-3": "#acacac",
  "--ledger-series-4": "#ed514e",
  "--ledger-series-5": "#d0d0d0",
  "--ledger-accent": "#ed514e",
  "--ledger-primary": "#191919",
  "--ledger-primary-hover": "#2c2c2c",
  "--ledger-hover": "#eeeeed",
  "--ledger-stripe": "#f8f8f8",
  "--ledger-selected": "#f1f1f0",
  "--ledger-border": "#e4e4e4",
  "--ledger-radius-shell": "46px",
  "--ledger-radius-panel": "34px",
  "--ledger-radius-card": "22px",
  "--ledger-radius-control": "14px",
  "--ledger-radius-nested": "11px",
  "--ledger-radius-range": "7px",
  "--ledger-corner-smoothing": "0.6",
  "--ledger-space-inset": "3px",
  "--ledger-space-small": "7px",
  "--ledger-space-control": "10px",
  "--ledger-space-panel": "20px",
  "--ledger-space-shell": "14px",
  "--ledger-shadow-panel": "drop-shadow(0 1px 1px rgb(0 0 0 / 0.2)) drop-shadow(0 12px 24px rgb(0 0 0 / 0.1))",
  "--ledger-shadow-floating": "drop-shadow(0 2px 3px rgb(0 0 0 / 0.14)) drop-shadow(0 24px 72px rgb(0 0 0 / 0.16))",
  "--ledger-shadow-tooltip": "drop-shadow(0 9px 22px rgb(0 0 0 / 0.24))",
  "--ledger-motion-enter": `${ledgerMotion.enter.duration * 1000}ms`,
  "--ledger-motion-exit": `${ledgerMotion.exit.duration * 1000}ms`,
  "--ledger-motion-summary": `${ledgerMotion.summary.duration * 1000}ms`,
  "--ledger-motion-chart": `${ledgerMotion.chart.duration * 1000}ms`,
  "--ledger-motion-hover": "160ms",
  "--ledger-motion-row": "150ms",
  "--ledger-ease-enter": `cubic-bezier(${ledgerMotion.enter.ease.join(", ")})`,
  "--ledger-ease-exit": `cubic-bezier(${ledgerMotion.exit.ease.join(", ")})`,
  "--ledger-table-row-height": "35px",
  "--ledger-table-header-height": "43px",
  "--ledger-table-font-size": "11px",
  "--ledger-table-label-size": "9px",
  "--ledger-table-cell-padding": "9px",
  "--ledger-table-trailing-width": "32px",
  "--ledger-control-height": "34px",
  "--ledger-heading-size": "36px",
  "--ledger-display-size": "51px",
  "--ledger-chart-width": "340",
  "--ledger-chart-height": "112",
  "--ledger-chart-inset": "12",
  "--ledger-chart-samples": "128",
  "--ledger-chart-line": "#e2e2e2",
  "--ledger-chart-baseline": "#3b3b3b",
  "--ledger-chart-rule": "#666666",
  "--ledger-chart-fill": "#bcbcbc",
  "--ledger-chart-tooltip": "rgba(20, 20, 20, 0.96)",
  "--ledger-chart-tooltip-border": "#464646",
  "--ledger-chart-tooltip-width": "130px",
};
